# Generated by Django 3.1.2 on 2020-10-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('cod_processo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('arq', models.FileField(upload_to='pdf/')),
                ('tema', models.IntegerField()),
            ],
            options={
                'ordering': ('numero',),
            },
        ),
    ]
