# Generated by Django 3.1.2 on 2020-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('cod_processo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=6)),
                ('arq', models.FileField(upload_to='pdf/<django.db.models.fields.CharField>/')),
                ('tema', models.CharField(choices=[(0, '1007'), (1, 'OUTROS')], default=1, max_length=1)),
            ],
            options={
                'ordering': ('numero',),
            },
        ),
    ]
