# Generated by Django 3.1.2 on 2020-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_auto_20201020_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='apontamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
