# Generated by Django 3.1.2 on 2020-10-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_auto_20201018_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
